[package]
name = "tonic-generator"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
prost-build = { workspace = true }
tonic-build = { workspace = true }
tonic-pool-build = { path = "../tonic-pool-build" }

tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
