[package]
name = "example-server"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
rand = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true }
tracing-subscriber = "0.3"

example-protobuf = { path = "../example-protobuf.gen" }
