[package]
name = "example-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.11"
futures = "0.3"
rand = "0.9"
scan_fmt = "0.2"

example-protobuf = { path = "../example-protobuf.gen" }
