[package]
name = "example-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.11"
rand = "0.9"

example-protobuf = { path = "../example-protobuf.gen" }
