[workspace]
resolver = "3"
members = [
    "auto-discovery",
    "example-client",
    "example-protobuf.gen",
    "example-server",
    "perf-benchmark",
    "tonic-generator",
]

package.edition = "2024"

[workspace.dependencies]
chrono = "0.4"
colog = "1"
http = "1"
prost = "0.13"
prost-build = "0.13"
rand = "0.9"
rstest = "0.25"
tokio = "1"
tonic = "0.12"
tonic-build = "0.12"
tracing = "0.1"
url = "2"
# I do not understand why example-protobuf.gen needs this dependency, and an older version at that,
# but without it, tokio panics with an integer overflow when operating on Instants and Durations.
tower = "0.4"
