[package]
name = "example-protobuf"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
http = { workspace = true }
prost = { workspace = true }
tonic = { workspace = true }

auto-discovery = { path = "../auto-discovery" }
