[package]
name = "example-protobuf"
version = "0.1.0"
edition = { workspace = true }
publish = false

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }

soda-pool = { path = "../../soda-pool" }
