[package]
name = "example-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.11"
futures = "0.3"
url = "2.5"
tracing = "0.1"
colog = "1.3"

example-protobuf = { path = "../example-protobuf.gen" }
auto-discovery = { path = "../auto-discovery" }
