[package]
name = "auto-discovery"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11"
prost = "0.12"
http-body = "0.4"
bytes = "1.6"
tower-service = "0.3"
http = "0.2"
hyper = "0.14"
tower = "0.4"
tokio = "1.0"
tokio-stream = "0.1"
futures-core = "0.3"
futures-util = "0.3"
tracing = "0.1"
rand = "0.9"
url = "2.5"

[features]
mock-dns = []

[dev-dependencies]
rstest = "0.25"
