[package]
name = "auto-discovery"
version = "0.1.0"
edition = "2024"

[dependencies]
http = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[features]
mock-dns = []

[dev-dependencies]
rstest = { workspace = true }
